(define (problem p09-tv-ds1-one-dev)
 (:domain entertainment)
 (:objects
  scart-to-cinch-cable-1 cinch-cable-1 cinch-cable-2 cinch-cable-3 cinch-cable-4 hdmi-cable-1 hdmi-cable-2 dvi-cable-1 hdmi-dvi-cable-1 headphone-cinch-cable-1 hdmi-dvip-cable-1 hdmi-dvip-cable-2 spdif-cable-1 blu-ray-1 sat-receiver-1 tv-1 amplifier-1 - equipment
  scart-to-cinch-cable-1-scart-1 scart-to-cinch-cable-1-cinch-2 scart-to-cinch-cable-1-cinch-3 cinch-cable-1-cinch-1 cinch-cable-1-cinch-2 cinch-cable-2-cinch-1 cinch-cable-2-cinch-2 cinch-cable-3-cinch-1 cinch-cable-3-cinch-2 cinch-cable-4-cinch-1 cinch-cable-4-cinch-2 hdmi-cable-1-hdmi-1 hdmi-cable-1-hdmi-2 hdmi-cable-2-hdmi-1 hdmi-cable-2-hdmi-2 dvi-cable-1-dvi-1 dvi-cable-1-dvi-2 hdmi-dvi-cable-1-hdmi-1 hdmi-dvi-cable-1-dvi-2 headphone-cinch-cable-1-cinch-1 headphone-cinch-cable-1-headphone-2 hdmi-dvip-cable-1-hdmi-1 hdmi-dvip-cable-1-dvi-2 hdmi-dvip-cable-2-hdmi-1 hdmi-dvip-cable-2-dvi-2 spdif-cable-1-spdif-1 spdif-cable-1-spdif-2 blu-ray-1-hdmi-1 blu-ray-1-cinch-2 blu-ray-1-cinch-3 sat-receiver-1-scart-1 sat-receiver-1-scart-2 sat-receiver-1-scart-3 sat-receiver-1-cinch-4 sat-receiver-1-cinch-5 sat-receiver-1-cinch-6 tv-1-hdmi-1 tv-1-hdmi-2 tv-1-hdmi-3 tv-1-hdmi-4 tv-1-cinch-5 tv-1-cinch-6 tv-1-vga-7 tv-1-headphone-8 tv-1-spdif-9 amplifier-1-cinch-1 amplifier-1-cinch-2 amplifier-1-cinch-3 amplifier-1-cinch-4 amplifier-1-cinch-5 amplifier-1-cinch-6 amplifier-1-cinch-7 amplifier-1-speakerWire-8 amplifier-1-speakerWire-9 amplifier-1-speakerWire-10 amplifier-1-speakerWire-11 amplifier-1-speakerWire-12 amplifier-1-hdmi-13 amplifier-1-hdmi-14 amplifier-1-hdmi-15 amplifier-1-hdmi-16 amplifier-1-hdmi-17 amplifier-1-hdmi-18 amplifier-1-hdmi-19 amplifier-1-spdif-20 - connector
 )
 (:htn
  :ordered-tasks (and
     (a_connect blu-ray-1 amplifier-1)
     (v_connect blu-ray-1 tv-1)
   )
  :ordering ( )
  :constraints ( ))
 (:init
  ;; device scart-to-cinch-cable-1
  (conn_of scart-to-cinch-cable-1 scart-to-cinch-cable-1-scart-1)
  (unused scart-to-cinch-cable-1-scart-1)
  (out_connector scart-to-cinch-cable-1-scart-1)
  (in_connector scart-to-cinch-cable-1-scart-1)
  (audio_connector scart-to-cinch-cable-1-scart-1)
  (video_connector scart-to-cinch-cable-1-scart-1)
  (conn_of scart-to-cinch-cable-1 scart-to-cinch-cable-1-cinch-2)
  (unused scart-to-cinch-cable-1-cinch-2)
  (out_connector scart-to-cinch-cable-1-cinch-2)
  (in_connector scart-to-cinch-cable-1-cinch-2)
  (audio_connector scart-to-cinch-cable-1-cinch-2)
  (conn_of scart-to-cinch-cable-1 scart-to-cinch-cable-1-cinch-3)
  (unused scart-to-cinch-cable-1-cinch-3)
  (out_connector scart-to-cinch-cable-1-cinch-3)
  (in_connector scart-to-cinch-cable-1-cinch-3)
  (video_connector scart-to-cinch-cable-1-cinch-3)

  ;; device cinch-cable-1
  (conn_of cinch-cable-1 cinch-cable-1-cinch-1)
  (unused cinch-cable-1-cinch-1)
  (in_connector cinch-cable-1-cinch-1)
  (audio_connector cinch-cable-1-cinch-1)
  (video_connector cinch-cable-1-cinch-1)
  (conn_of cinch-cable-1 cinch-cable-1-cinch-2)
  (unused cinch-cable-1-cinch-2)
  (out_connector cinch-cable-1-cinch-2)
  (audio_connector cinch-cable-1-cinch-2)
  (video_connector cinch-cable-1-cinch-2)

  ;; device cinch-cable-2
  (conn_of cinch-cable-2 cinch-cable-2-cinch-1)
  (unused cinch-cable-2-cinch-1)
  (in_connector cinch-cable-2-cinch-1)
  (audio_connector cinch-cable-2-cinch-1)
  (video_connector cinch-cable-2-cinch-1)
  (conn_of cinch-cable-2 cinch-cable-2-cinch-2)
  (unused cinch-cable-2-cinch-2)
  (out_connector cinch-cable-2-cinch-2)
  (audio_connector cinch-cable-2-cinch-2)
  (video_connector cinch-cable-2-cinch-2)

  ;; device cinch-cable-3
  (conn_of cinch-cable-3 cinch-cable-3-cinch-1)
  (unused cinch-cable-3-cinch-1)
  (in_connector cinch-cable-3-cinch-1)
  (audio_connector cinch-cable-3-cinch-1)
  (video_connector cinch-cable-3-cinch-1)
  (conn_of cinch-cable-3 cinch-cable-3-cinch-2)
  (unused cinch-cable-3-cinch-2)
  (out_connector cinch-cable-3-cinch-2)
  (audio_connector cinch-cable-3-cinch-2)
  (video_connector cinch-cable-3-cinch-2)

  ;; device cinch-cable-4
  (conn_of cinch-cable-4 cinch-cable-4-cinch-1)
  (unused cinch-cable-4-cinch-1)
  (in_connector cinch-cable-4-cinch-1)
  (audio_connector cinch-cable-4-cinch-1)
  (video_connector cinch-cable-4-cinch-1)
  (conn_of cinch-cable-4 cinch-cable-4-cinch-2)
  (unused cinch-cable-4-cinch-2)
  (out_connector cinch-cable-4-cinch-2)
  (audio_connector cinch-cable-4-cinch-2)
  (video_connector cinch-cable-4-cinch-2)

  ;; device hdmi-cable-1
  (conn_of hdmi-cable-1 hdmi-cable-1-hdmi-1)
  (unused hdmi-cable-1-hdmi-1)
  (in_connector hdmi-cable-1-hdmi-1)
  (audio_connector hdmi-cable-1-hdmi-1)
  (video_connector hdmi-cable-1-hdmi-1)
  (conn_of hdmi-cable-1 hdmi-cable-1-hdmi-2)
  (unused hdmi-cable-1-hdmi-2)
  (out_connector hdmi-cable-1-hdmi-2)
  (audio_connector hdmi-cable-1-hdmi-2)
  (video_connector hdmi-cable-1-hdmi-2)

  ;; device hdmi-cable-2
  (conn_of hdmi-cable-2 hdmi-cable-2-hdmi-1)
  (unused hdmi-cable-2-hdmi-1)
  (in_connector hdmi-cable-2-hdmi-1)
  (audio_connector hdmi-cable-2-hdmi-1)
  (video_connector hdmi-cable-2-hdmi-1)
  (conn_of hdmi-cable-2 hdmi-cable-2-hdmi-2)
  (unused hdmi-cable-2-hdmi-2)
  (out_connector hdmi-cable-2-hdmi-2)
  (audio_connector hdmi-cable-2-hdmi-2)
  (video_connector hdmi-cable-2-hdmi-2)

  ;; device dvi-cable-1
  (conn_of dvi-cable-1 dvi-cable-1-dvi-1)
  (unused dvi-cable-1-dvi-1)
  (in_connector dvi-cable-1-dvi-1)
  (video_connector dvi-cable-1-dvi-1)
  (conn_of dvi-cable-1 dvi-cable-1-dvi-2)
  (unused dvi-cable-1-dvi-2)
  (out_connector dvi-cable-1-dvi-2)
  (video_connector dvi-cable-1-dvi-2)

  ;; device hdmi-dvi-cable-1
  (conn_of hdmi-dvi-cable-1 hdmi-dvi-cable-1-hdmi-1)
  (unused hdmi-dvi-cable-1-hdmi-1)
  (out_connector hdmi-dvi-cable-1-hdmi-1)
  (in_connector hdmi-dvi-cable-1-hdmi-1)
  (video_connector hdmi-dvi-cable-1-hdmi-1)
  (conn_of hdmi-dvi-cable-1 hdmi-dvi-cable-1-dvi-2)
  (unused hdmi-dvi-cable-1-dvi-2)
  (out_connector hdmi-dvi-cable-1-dvi-2)
  (in_connector hdmi-dvi-cable-1-dvi-2)
  (video_connector hdmi-dvi-cable-1-dvi-2)

  ;; device headphone-cinch-cable-1
  (conn_of headphone-cinch-cable-1 headphone-cinch-cable-1-cinch-1)
  (unused headphone-cinch-cable-1-cinch-1)
  (out_connector headphone-cinch-cable-1-cinch-1)
  (in_connector headphone-cinch-cable-1-cinch-1)
  (audio_connector headphone-cinch-cable-1-cinch-1)
  (conn_of headphone-cinch-cable-1 headphone-cinch-cable-1-headphone-2)
  (unused headphone-cinch-cable-1-headphone-2)
  (out_connector headphone-cinch-cable-1-headphone-2)
  (in_connector headphone-cinch-cable-1-headphone-2)
  (audio_connector headphone-cinch-cable-1-headphone-2)

  ;; device hdmi-dvip-cable-1
  (conn_of hdmi-dvip-cable-1 hdmi-dvip-cable-1-hdmi-1)
  (unused hdmi-dvip-cable-1-hdmi-1)
  (out_connector hdmi-dvip-cable-1-hdmi-1)
  (in_connector hdmi-dvip-cable-1-hdmi-1)
  (video_connector hdmi-dvip-cable-1-hdmi-1)
  (conn_of hdmi-dvip-cable-1 hdmi-dvip-cable-1-dvi-2)
  (unused hdmi-dvip-cable-1-dvi-2)
  (out_connector hdmi-dvip-cable-1-dvi-2)
  (in_connector hdmi-dvip-cable-1-dvi-2)
  (video_connector hdmi-dvip-cable-1-dvi-2)

  ;; device hdmi-dvip-cable-2
  (conn_of hdmi-dvip-cable-2 hdmi-dvip-cable-2-hdmi-1)
  (unused hdmi-dvip-cable-2-hdmi-1)
  (out_connector hdmi-dvip-cable-2-hdmi-1)
  (in_connector hdmi-dvip-cable-2-hdmi-1)
  (video_connector hdmi-dvip-cable-2-hdmi-1)
  (conn_of hdmi-dvip-cable-2 hdmi-dvip-cable-2-dvi-2)
  (unused hdmi-dvip-cable-2-dvi-2)
  (out_connector hdmi-dvip-cable-2-dvi-2)
  (in_connector hdmi-dvip-cable-2-dvi-2)
  (video_connector hdmi-dvip-cable-2-dvi-2)

  ;; device spdif-cable-1
  (conn_of spdif-cable-1 spdif-cable-1-spdif-1)
  (unused spdif-cable-1-spdif-1)
  (in_connector spdif-cable-1-spdif-1)
  (audio_connector spdif-cable-1-spdif-1)
  (conn_of spdif-cable-1 spdif-cable-1-spdif-2)
  (unused spdif-cable-1-spdif-2)
  (out_connector spdif-cable-1-spdif-2)
  (audio_connector spdif-cable-1-spdif-2)

  ;; device blu-ray-1
  (conn_of blu-ray-1 blu-ray-1-hdmi-1)
  (unused blu-ray-1-hdmi-1)
  (out_connector blu-ray-1-hdmi-1)
  (audio_connector blu-ray-1-hdmi-1)
  (video_connector blu-ray-1-hdmi-1)
  (conn_of blu-ray-1 blu-ray-1-cinch-2)
  (unused blu-ray-1-cinch-2)
  (out_connector blu-ray-1-cinch-2)
  (audio_connector blu-ray-1-cinch-2)
  (conn_of blu-ray-1 blu-ray-1-cinch-3)
  (unused blu-ray-1-cinch-3)
  (out_connector blu-ray-1-cinch-3)
  (video_connector blu-ray-1-cinch-3)

  ;; device sat-receiver-1
  (conn_of sat-receiver-1 sat-receiver-1-scart-1)
  (unused sat-receiver-1-scart-1)
  (out_connector sat-receiver-1-scart-1)
  (audio_connector sat-receiver-1-scart-1)
  (video_connector sat-receiver-1-scart-1)
  (conn_of sat-receiver-1 sat-receiver-1-scart-2)
  (unused sat-receiver-1-scart-2)
  (out_connector sat-receiver-1-scart-2)
  (audio_connector sat-receiver-1-scart-2)
  (video_connector sat-receiver-1-scart-2)
  (conn_of sat-receiver-1 sat-receiver-1-scart-3)
  (unused sat-receiver-1-scart-3)
  (out_connector sat-receiver-1-scart-3)
  (audio_connector sat-receiver-1-scart-3)
  (video_connector sat-receiver-1-scart-3)
  (conn_of sat-receiver-1 sat-receiver-1-cinch-4)
  (unused sat-receiver-1-cinch-4)
  (out_connector sat-receiver-1-cinch-4)
  (video_connector sat-receiver-1-cinch-4)
  (conn_of sat-receiver-1 sat-receiver-1-cinch-5)
  (unused sat-receiver-1-cinch-5)
  (out_connector sat-receiver-1-cinch-5)
  (video_connector sat-receiver-1-cinch-5)
  (conn_of sat-receiver-1 sat-receiver-1-cinch-6)
  (unused sat-receiver-1-cinch-6)
  (out_connector sat-receiver-1-cinch-6)
  (audio_connector sat-receiver-1-cinch-6)

  ;; device tv-1
  (conn_of tv-1 tv-1-hdmi-1)
  (unused tv-1-hdmi-1)
  (in_connector tv-1-hdmi-1)
  (audio_connector tv-1-hdmi-1)
  (video_connector tv-1-hdmi-1)
  (conn_of tv-1 tv-1-hdmi-2)
  (unused tv-1-hdmi-2)
  (in_connector tv-1-hdmi-2)
  (audio_connector tv-1-hdmi-2)
  (video_connector tv-1-hdmi-2)
  (conn_of tv-1 tv-1-hdmi-3)
  (unused tv-1-hdmi-3)
  (in_connector tv-1-hdmi-3)
  (audio_connector tv-1-hdmi-3)
  (video_connector tv-1-hdmi-3)
  (conn_of tv-1 tv-1-hdmi-4)
  (unused tv-1-hdmi-4)
  (in_connector tv-1-hdmi-4)
  (audio_connector tv-1-hdmi-4)
  (video_connector tv-1-hdmi-4)
  (conn_of tv-1 tv-1-cinch-5)
  (unused tv-1-cinch-5)
  (in_connector tv-1-cinch-5)
  (audio_connector tv-1-cinch-5)
  (conn_of tv-1 tv-1-cinch-6)
  (unused tv-1-cinch-6)
  (in_connector tv-1-cinch-6)
  (video_connector tv-1-cinch-6)
  (conn_of tv-1 tv-1-vga-7)
  (unused tv-1-vga-7)
  (in_connector tv-1-vga-7)
  (video_connector tv-1-vga-7)
  (conn_of tv-1 tv-1-headphone-8)
  (unused tv-1-headphone-8)
  (in_connector tv-1-headphone-8)
  (audio_connector tv-1-headphone-8)
  (conn_of tv-1 tv-1-spdif-9)
  (unused tv-1-spdif-9)
  (in_connector tv-1-spdif-9)
  (audio_connector tv-1-spdif-9)

  ;; device amplifier-1
  (conn_of amplifier-1 amplifier-1-cinch-1)
  (unused amplifier-1-cinch-1)
  (in_connector amplifier-1-cinch-1)
  (audio_connector amplifier-1-cinch-1)
  (conn_of amplifier-1 amplifier-1-cinch-2)
  (unused amplifier-1-cinch-2)
  (in_connector amplifier-1-cinch-2)
  (audio_connector amplifier-1-cinch-2)
  (conn_of amplifier-1 amplifier-1-cinch-3)
  (unused amplifier-1-cinch-3)
  (in_connector amplifier-1-cinch-3)
  (audio_connector amplifier-1-cinch-3)
  (conn_of amplifier-1 amplifier-1-cinch-4)
  (unused amplifier-1-cinch-4)
  (in_connector amplifier-1-cinch-4)
  (audio_connector amplifier-1-cinch-4)
  (conn_of amplifier-1 amplifier-1-cinch-5)
  (unused amplifier-1-cinch-5)
  (in_connector amplifier-1-cinch-5)
  (video_connector amplifier-1-cinch-5)
  (conn_of amplifier-1 amplifier-1-cinch-6)
  (unused amplifier-1-cinch-6)
  (in_connector amplifier-1-cinch-6)
  (video_connector amplifier-1-cinch-6)
  (conn_of amplifier-1 amplifier-1-cinch-7)
  (unused amplifier-1-cinch-7)
  (out_connector amplifier-1-cinch-7)
  (video_connector amplifier-1-cinch-7)
  (conn_of amplifier-1 amplifier-1-speakerWire-8)
  (unused amplifier-1-speakerWire-8)
  (out_connector amplifier-1-speakerWire-8)
  (audio_connector amplifier-1-speakerWire-8)
  (conn_of amplifier-1 amplifier-1-speakerWire-9)
  (unused amplifier-1-speakerWire-9)
  (out_connector amplifier-1-speakerWire-9)
  (audio_connector amplifier-1-speakerWire-9)
  (conn_of amplifier-1 amplifier-1-speakerWire-10)
  (unused amplifier-1-speakerWire-10)
  (out_connector amplifier-1-speakerWire-10)
  (audio_connector amplifier-1-speakerWire-10)
  (conn_of amplifier-1 amplifier-1-speakerWire-11)
  (unused amplifier-1-speakerWire-11)
  (out_connector amplifier-1-speakerWire-11)
  (audio_connector amplifier-1-speakerWire-11)
  (conn_of amplifier-1 amplifier-1-speakerWire-12)
  (unused amplifier-1-speakerWire-12)
  (out_connector amplifier-1-speakerWire-12)
  (audio_connector amplifier-1-speakerWire-12)
  (conn_of amplifier-1 amplifier-1-hdmi-13)
  (unused amplifier-1-hdmi-13)
  (in_connector amplifier-1-hdmi-13)
  (audio_connector amplifier-1-hdmi-13)
  (video_connector amplifier-1-hdmi-13)
  (conn_of amplifier-1 amplifier-1-hdmi-14)
  (unused amplifier-1-hdmi-14)
  (in_connector amplifier-1-hdmi-14)
  (audio_connector amplifier-1-hdmi-14)
  (video_connector amplifier-1-hdmi-14)
  (conn_of amplifier-1 amplifier-1-hdmi-15)
  (unused amplifier-1-hdmi-15)
  (in_connector amplifier-1-hdmi-15)
  (audio_connector amplifier-1-hdmi-15)
  (video_connector amplifier-1-hdmi-15)
  (conn_of amplifier-1 amplifier-1-hdmi-16)
  (unused amplifier-1-hdmi-16)
  (in_connector amplifier-1-hdmi-16)
  (audio_connector amplifier-1-hdmi-16)
  (video_connector amplifier-1-hdmi-16)
  (conn_of amplifier-1 amplifier-1-hdmi-17)
  (unused amplifier-1-hdmi-17)
  (in_connector amplifier-1-hdmi-17)
  (audio_connector amplifier-1-hdmi-17)
  (video_connector amplifier-1-hdmi-17)
  (conn_of amplifier-1 amplifier-1-hdmi-18)
  (unused amplifier-1-hdmi-18)
  (in_connector amplifier-1-hdmi-18)
  (audio_connector amplifier-1-hdmi-18)
  (video_connector amplifier-1-hdmi-18)
  (conn_of amplifier-1 amplifier-1-hdmi-19)
  (unused amplifier-1-hdmi-19)
  (out_connector amplifier-1-hdmi-19)
  (audio_connector amplifier-1-hdmi-19)
  (video_connector amplifier-1-hdmi-19)
  (conn_of amplifier-1 amplifier-1-spdif-20)
  (unused amplifier-1-spdif-20)
  (in_connector amplifier-1-spdif-20)
  (audio_connector amplifier-1-spdif-20)

  ;; compatibility of connections
  (compatible scart-to-cinch-cable-1-scart-1 sat-receiver-1-scart-1)
  (compatible scart-to-cinch-cable-1-scart-1 sat-receiver-1-scart-2)
  (compatible scart-to-cinch-cable-1-scart-1 sat-receiver-1-scart-3)
  (compatible scart-to-cinch-cable-1-cinch-2 blu-ray-1-cinch-2)
  (compatible scart-to-cinch-cable-1-cinch-2 blu-ray-1-cinch-3)
  (compatible scart-to-cinch-cable-1-cinch-2 sat-receiver-1-cinch-4)
  (compatible scart-to-cinch-cable-1-cinch-2 sat-receiver-1-cinch-5)
  (compatible scart-to-cinch-cable-1-cinch-2 sat-receiver-1-cinch-6)
  (compatible scart-to-cinch-cable-1-cinch-2 tv-1-cinch-5)
  (compatible scart-to-cinch-cable-1-cinch-2 tv-1-cinch-6)
  (compatible scart-to-cinch-cable-1-cinch-2 amplifier-1-cinch-1)
  (compatible scart-to-cinch-cable-1-cinch-2 amplifier-1-cinch-2)
  (compatible scart-to-cinch-cable-1-cinch-2 amplifier-1-cinch-3)
  (compatible scart-to-cinch-cable-1-cinch-2 amplifier-1-cinch-4)
  (compatible scart-to-cinch-cable-1-cinch-2 amplifier-1-cinch-5)
  (compatible scart-to-cinch-cable-1-cinch-2 amplifier-1-cinch-6)
  (compatible scart-to-cinch-cable-1-cinch-2 amplifier-1-cinch-7)
  (compatible scart-to-cinch-cable-1-cinch-3 blu-ray-1-cinch-2)
  (compatible scart-to-cinch-cable-1-cinch-3 blu-ray-1-cinch-3)
  (compatible scart-to-cinch-cable-1-cinch-3 sat-receiver-1-cinch-4)
  (compatible scart-to-cinch-cable-1-cinch-3 sat-receiver-1-cinch-5)
  (compatible scart-to-cinch-cable-1-cinch-3 sat-receiver-1-cinch-6)
  (compatible scart-to-cinch-cable-1-cinch-3 tv-1-cinch-5)
  (compatible scart-to-cinch-cable-1-cinch-3 tv-1-cinch-6)
  (compatible scart-to-cinch-cable-1-cinch-3 amplifier-1-cinch-1)
  (compatible scart-to-cinch-cable-1-cinch-3 amplifier-1-cinch-2)
  (compatible scart-to-cinch-cable-1-cinch-3 amplifier-1-cinch-3)
  (compatible scart-to-cinch-cable-1-cinch-3 amplifier-1-cinch-4)
  (compatible scart-to-cinch-cable-1-cinch-3 amplifier-1-cinch-5)
  (compatible scart-to-cinch-cable-1-cinch-3 amplifier-1-cinch-6)
  (compatible scart-to-cinch-cable-1-cinch-3 amplifier-1-cinch-7)
  (compatible cinch-cable-1-cinch-1 blu-ray-1-cinch-2)
  (compatible cinch-cable-1-cinch-1 blu-ray-1-cinch-3)
  (compatible cinch-cable-1-cinch-1 sat-receiver-1-cinch-4)
  (compatible cinch-cable-1-cinch-1 sat-receiver-1-cinch-5)
  (compatible cinch-cable-1-cinch-1 sat-receiver-1-cinch-6)
  (compatible cinch-cable-1-cinch-1 tv-1-cinch-5)
  (compatible cinch-cable-1-cinch-1 tv-1-cinch-6)
  (compatible cinch-cable-1-cinch-1 amplifier-1-cinch-1)
  (compatible cinch-cable-1-cinch-1 amplifier-1-cinch-2)
  (compatible cinch-cable-1-cinch-1 amplifier-1-cinch-3)
  (compatible cinch-cable-1-cinch-1 amplifier-1-cinch-4)
  (compatible cinch-cable-1-cinch-1 amplifier-1-cinch-5)
  (compatible cinch-cable-1-cinch-1 amplifier-1-cinch-6)
  (compatible cinch-cable-1-cinch-1 amplifier-1-cinch-7)
  (compatible cinch-cable-1-cinch-2 blu-ray-1-cinch-2)
  (compatible cinch-cable-1-cinch-2 blu-ray-1-cinch-3)
  (compatible cinch-cable-1-cinch-2 sat-receiver-1-cinch-4)
  (compatible cinch-cable-1-cinch-2 sat-receiver-1-cinch-5)
  (compatible cinch-cable-1-cinch-2 sat-receiver-1-cinch-6)
  (compatible cinch-cable-1-cinch-2 tv-1-cinch-5)
  (compatible cinch-cable-1-cinch-2 tv-1-cinch-6)
  (compatible cinch-cable-1-cinch-2 amplifier-1-cinch-1)
  (compatible cinch-cable-1-cinch-2 amplifier-1-cinch-2)
  (compatible cinch-cable-1-cinch-2 amplifier-1-cinch-3)
  (compatible cinch-cable-1-cinch-2 amplifier-1-cinch-4)
  (compatible cinch-cable-1-cinch-2 amplifier-1-cinch-5)
  (compatible cinch-cable-1-cinch-2 amplifier-1-cinch-6)
  (compatible cinch-cable-1-cinch-2 amplifier-1-cinch-7)
  (compatible cinch-cable-2-cinch-1 blu-ray-1-cinch-2)
  (compatible cinch-cable-2-cinch-1 blu-ray-1-cinch-3)
  (compatible cinch-cable-2-cinch-1 sat-receiver-1-cinch-4)
  (compatible cinch-cable-2-cinch-1 sat-receiver-1-cinch-5)
  (compatible cinch-cable-2-cinch-1 sat-receiver-1-cinch-6)
  (compatible cinch-cable-2-cinch-1 tv-1-cinch-5)
  (compatible cinch-cable-2-cinch-1 tv-1-cinch-6)
  (compatible cinch-cable-2-cinch-1 amplifier-1-cinch-1)
  (compatible cinch-cable-2-cinch-1 amplifier-1-cinch-2)
  (compatible cinch-cable-2-cinch-1 amplifier-1-cinch-3)
  (compatible cinch-cable-2-cinch-1 amplifier-1-cinch-4)
  (compatible cinch-cable-2-cinch-1 amplifier-1-cinch-5)
  (compatible cinch-cable-2-cinch-1 amplifier-1-cinch-6)
  (compatible cinch-cable-2-cinch-1 amplifier-1-cinch-7)
  (compatible cinch-cable-2-cinch-2 blu-ray-1-cinch-2)
  (compatible cinch-cable-2-cinch-2 blu-ray-1-cinch-3)
  (compatible cinch-cable-2-cinch-2 sat-receiver-1-cinch-4)
  (compatible cinch-cable-2-cinch-2 sat-receiver-1-cinch-5)
  (compatible cinch-cable-2-cinch-2 sat-receiver-1-cinch-6)
  (compatible cinch-cable-2-cinch-2 tv-1-cinch-5)
  (compatible cinch-cable-2-cinch-2 tv-1-cinch-6)
  (compatible cinch-cable-2-cinch-2 amplifier-1-cinch-1)
  (compatible cinch-cable-2-cinch-2 amplifier-1-cinch-2)
  (compatible cinch-cable-2-cinch-2 amplifier-1-cinch-3)
  (compatible cinch-cable-2-cinch-2 amplifier-1-cinch-4)
  (compatible cinch-cable-2-cinch-2 amplifier-1-cinch-5)
  (compatible cinch-cable-2-cinch-2 amplifier-1-cinch-6)
  (compatible cinch-cable-2-cinch-2 amplifier-1-cinch-7)
  (compatible cinch-cable-3-cinch-1 blu-ray-1-cinch-2)
  (compatible cinch-cable-3-cinch-1 blu-ray-1-cinch-3)
  (compatible cinch-cable-3-cinch-1 sat-receiver-1-cinch-4)
  (compatible cinch-cable-3-cinch-1 sat-receiver-1-cinch-5)
  (compatible cinch-cable-3-cinch-1 sat-receiver-1-cinch-6)
  (compatible cinch-cable-3-cinch-1 tv-1-cinch-5)
  (compatible cinch-cable-3-cinch-1 tv-1-cinch-6)
  (compatible cinch-cable-3-cinch-1 amplifier-1-cinch-1)
  (compatible cinch-cable-3-cinch-1 amplifier-1-cinch-2)
  (compatible cinch-cable-3-cinch-1 amplifier-1-cinch-3)
  (compatible cinch-cable-3-cinch-1 amplifier-1-cinch-4)
  (compatible cinch-cable-3-cinch-1 amplifier-1-cinch-5)
  (compatible cinch-cable-3-cinch-1 amplifier-1-cinch-6)
  (compatible cinch-cable-3-cinch-1 amplifier-1-cinch-7)
  (compatible cinch-cable-3-cinch-2 blu-ray-1-cinch-2)
  (compatible cinch-cable-3-cinch-2 blu-ray-1-cinch-3)
  (compatible cinch-cable-3-cinch-2 sat-receiver-1-cinch-4)
  (compatible cinch-cable-3-cinch-2 sat-receiver-1-cinch-5)
  (compatible cinch-cable-3-cinch-2 sat-receiver-1-cinch-6)
  (compatible cinch-cable-3-cinch-2 tv-1-cinch-5)
  (compatible cinch-cable-3-cinch-2 tv-1-cinch-6)
  (compatible cinch-cable-3-cinch-2 amplifier-1-cinch-1)
  (compatible cinch-cable-3-cinch-2 amplifier-1-cinch-2)
  (compatible cinch-cable-3-cinch-2 amplifier-1-cinch-3)
  (compatible cinch-cable-3-cinch-2 amplifier-1-cinch-4)
  (compatible cinch-cable-3-cinch-2 amplifier-1-cinch-5)
  (compatible cinch-cable-3-cinch-2 amplifier-1-cinch-6)
  (compatible cinch-cable-3-cinch-2 amplifier-1-cinch-7)
  (compatible cinch-cable-4-cinch-1 blu-ray-1-cinch-2)
  (compatible cinch-cable-4-cinch-1 blu-ray-1-cinch-3)
  (compatible cinch-cable-4-cinch-1 sat-receiver-1-cinch-4)
  (compatible cinch-cable-4-cinch-1 sat-receiver-1-cinch-5)
  (compatible cinch-cable-4-cinch-1 sat-receiver-1-cinch-6)
  (compatible cinch-cable-4-cinch-1 tv-1-cinch-5)
  (compatible cinch-cable-4-cinch-1 tv-1-cinch-6)
  (compatible cinch-cable-4-cinch-1 amplifier-1-cinch-1)
  (compatible cinch-cable-4-cinch-1 amplifier-1-cinch-2)
  (compatible cinch-cable-4-cinch-1 amplifier-1-cinch-3)
  (compatible cinch-cable-4-cinch-1 amplifier-1-cinch-4)
  (compatible cinch-cable-4-cinch-1 amplifier-1-cinch-5)
  (compatible cinch-cable-4-cinch-1 amplifier-1-cinch-6)
  (compatible cinch-cable-4-cinch-1 amplifier-1-cinch-7)
  (compatible cinch-cable-4-cinch-2 blu-ray-1-cinch-2)
  (compatible cinch-cable-4-cinch-2 blu-ray-1-cinch-3)
  (compatible cinch-cable-4-cinch-2 sat-receiver-1-cinch-4)
  (compatible cinch-cable-4-cinch-2 sat-receiver-1-cinch-5)
  (compatible cinch-cable-4-cinch-2 sat-receiver-1-cinch-6)
  (compatible cinch-cable-4-cinch-2 tv-1-cinch-5)
  (compatible cinch-cable-4-cinch-2 tv-1-cinch-6)
  (compatible cinch-cable-4-cinch-2 amplifier-1-cinch-1)
  (compatible cinch-cable-4-cinch-2 amplifier-1-cinch-2)
  (compatible cinch-cable-4-cinch-2 amplifier-1-cinch-3)
  (compatible cinch-cable-4-cinch-2 amplifier-1-cinch-4)
  (compatible cinch-cable-4-cinch-2 amplifier-1-cinch-5)
  (compatible cinch-cable-4-cinch-2 amplifier-1-cinch-6)
  (compatible cinch-cable-4-cinch-2 amplifier-1-cinch-7)
  (compatible hdmi-cable-1-hdmi-1 blu-ray-1-hdmi-1)
  (compatible hdmi-cable-1-hdmi-1 tv-1-hdmi-1)
  (compatible hdmi-cable-1-hdmi-1 tv-1-hdmi-2)
  (compatible hdmi-cable-1-hdmi-1 tv-1-hdmi-3)
  (compatible hdmi-cable-1-hdmi-1 tv-1-hdmi-4)
  (compatible hdmi-cable-1-hdmi-1 amplifier-1-hdmi-13)
  (compatible hdmi-cable-1-hdmi-1 amplifier-1-hdmi-14)
  (compatible hdmi-cable-1-hdmi-1 amplifier-1-hdmi-15)
  (compatible hdmi-cable-1-hdmi-1 amplifier-1-hdmi-16)
  (compatible hdmi-cable-1-hdmi-1 amplifier-1-hdmi-17)
  (compatible hdmi-cable-1-hdmi-1 amplifier-1-hdmi-18)
  (compatible hdmi-cable-1-hdmi-1 amplifier-1-hdmi-19)
  (compatible hdmi-cable-1-hdmi-2 blu-ray-1-hdmi-1)
  (compatible hdmi-cable-1-hdmi-2 tv-1-hdmi-1)
  (compatible hdmi-cable-1-hdmi-2 tv-1-hdmi-2)
  (compatible hdmi-cable-1-hdmi-2 tv-1-hdmi-3)
  (compatible hdmi-cable-1-hdmi-2 tv-1-hdmi-4)
  (compatible hdmi-cable-1-hdmi-2 amplifier-1-hdmi-13)
  (compatible hdmi-cable-1-hdmi-2 amplifier-1-hdmi-14)
  (compatible hdmi-cable-1-hdmi-2 amplifier-1-hdmi-15)
  (compatible hdmi-cable-1-hdmi-2 amplifier-1-hdmi-16)
  (compatible hdmi-cable-1-hdmi-2 amplifier-1-hdmi-17)
  (compatible hdmi-cable-1-hdmi-2 amplifier-1-hdmi-18)
  (compatible hdmi-cable-1-hdmi-2 amplifier-1-hdmi-19)
  (compatible hdmi-cable-2-hdmi-1 blu-ray-1-hdmi-1)
  (compatible hdmi-cable-2-hdmi-1 tv-1-hdmi-1)
  (compatible hdmi-cable-2-hdmi-1 tv-1-hdmi-2)
  (compatible hdmi-cable-2-hdmi-1 tv-1-hdmi-3)
  (compatible hdmi-cable-2-hdmi-1 tv-1-hdmi-4)
  (compatible hdmi-cable-2-hdmi-1 amplifier-1-hdmi-13)
  (compatible hdmi-cable-2-hdmi-1 amplifier-1-hdmi-14)
  (compatible hdmi-cable-2-hdmi-1 amplifier-1-hdmi-15)
  (compatible hdmi-cable-2-hdmi-1 amplifier-1-hdmi-16)
  (compatible hdmi-cable-2-hdmi-1 amplifier-1-hdmi-17)
  (compatible hdmi-cable-2-hdmi-1 amplifier-1-hdmi-18)
  (compatible hdmi-cable-2-hdmi-1 amplifier-1-hdmi-19)
  (compatible hdmi-cable-2-hdmi-2 blu-ray-1-hdmi-1)
  (compatible hdmi-cable-2-hdmi-2 tv-1-hdmi-1)
  (compatible hdmi-cable-2-hdmi-2 tv-1-hdmi-2)
  (compatible hdmi-cable-2-hdmi-2 tv-1-hdmi-3)
  (compatible hdmi-cable-2-hdmi-2 tv-1-hdmi-4)
  (compatible hdmi-cable-2-hdmi-2 amplifier-1-hdmi-13)
  (compatible hdmi-cable-2-hdmi-2 amplifier-1-hdmi-14)
  (compatible hdmi-cable-2-hdmi-2 amplifier-1-hdmi-15)
  (compatible hdmi-cable-2-hdmi-2 amplifier-1-hdmi-16)
  (compatible hdmi-cable-2-hdmi-2 amplifier-1-hdmi-17)
  (compatible hdmi-cable-2-hdmi-2 amplifier-1-hdmi-18)
  (compatible hdmi-cable-2-hdmi-2 amplifier-1-hdmi-19)
  (compatible dvi-cable-1-dvi-1 hdmi-dvip-cable-1-dvi-2)
  (compatible dvi-cable-1-dvi-1 hdmi-dvip-cable-2-dvi-2)
  (compatible dvi-cable-1-dvi-2 hdmi-dvip-cable-1-dvi-2)
  (compatible dvi-cable-1-dvi-2 hdmi-dvip-cable-2-dvi-2)
  (compatible hdmi-dvi-cable-1-hdmi-1 blu-ray-1-hdmi-1)
  (compatible hdmi-dvi-cable-1-hdmi-1 tv-1-hdmi-1)
  (compatible hdmi-dvi-cable-1-hdmi-1 tv-1-hdmi-2)
  (compatible hdmi-dvi-cable-1-hdmi-1 tv-1-hdmi-3)
  (compatible hdmi-dvi-cable-1-hdmi-1 tv-1-hdmi-4)
  (compatible hdmi-dvi-cable-1-hdmi-1 amplifier-1-hdmi-13)
  (compatible hdmi-dvi-cable-1-hdmi-1 amplifier-1-hdmi-14)
  (compatible hdmi-dvi-cable-1-hdmi-1 amplifier-1-hdmi-15)
  (compatible hdmi-dvi-cable-1-hdmi-1 amplifier-1-hdmi-16)
  (compatible hdmi-dvi-cable-1-hdmi-1 amplifier-1-hdmi-17)
  (compatible hdmi-dvi-cable-1-hdmi-1 amplifier-1-hdmi-18)
  (compatible hdmi-dvi-cable-1-hdmi-1 amplifier-1-hdmi-19)
  (compatible hdmi-dvi-cable-1-dvi-2 hdmi-dvip-cable-1-dvi-2)
  (compatible hdmi-dvi-cable-1-dvi-2 hdmi-dvip-cable-2-dvi-2)
  (compatible headphone-cinch-cable-1-cinch-1 blu-ray-1-cinch-2)
  (compatible headphone-cinch-cable-1-cinch-1 blu-ray-1-cinch-3)
  (compatible headphone-cinch-cable-1-cinch-1 sat-receiver-1-cinch-4)
  (compatible headphone-cinch-cable-1-cinch-1 sat-receiver-1-cinch-5)
  (compatible headphone-cinch-cable-1-cinch-1 sat-receiver-1-cinch-6)
  (compatible headphone-cinch-cable-1-cinch-1 tv-1-cinch-5)
  (compatible headphone-cinch-cable-1-cinch-1 tv-1-cinch-6)
  (compatible headphone-cinch-cable-1-cinch-1 amplifier-1-cinch-1)
  (compatible headphone-cinch-cable-1-cinch-1 amplifier-1-cinch-2)
  (compatible headphone-cinch-cable-1-cinch-1 amplifier-1-cinch-3)
  (compatible headphone-cinch-cable-1-cinch-1 amplifier-1-cinch-4)
  (compatible headphone-cinch-cable-1-cinch-1 amplifier-1-cinch-5)
  (compatible headphone-cinch-cable-1-cinch-1 amplifier-1-cinch-6)
  (compatible headphone-cinch-cable-1-cinch-1 amplifier-1-cinch-7)
  (compatible headphone-cinch-cable-1-headphone-2 tv-1-headphone-8)
  (compatible hdmi-dvip-cable-1-hdmi-1 blu-ray-1-hdmi-1)
  (compatible hdmi-dvip-cable-1-hdmi-1 tv-1-hdmi-1)
  (compatible hdmi-dvip-cable-1-hdmi-1 tv-1-hdmi-2)
  (compatible hdmi-dvip-cable-1-hdmi-1 tv-1-hdmi-3)
  (compatible hdmi-dvip-cable-1-hdmi-1 tv-1-hdmi-4)
  (compatible hdmi-dvip-cable-1-hdmi-1 amplifier-1-hdmi-13)
  (compatible hdmi-dvip-cable-1-hdmi-1 amplifier-1-hdmi-14)
  (compatible hdmi-dvip-cable-1-hdmi-1 amplifier-1-hdmi-15)
  (compatible hdmi-dvip-cable-1-hdmi-1 amplifier-1-hdmi-16)
  (compatible hdmi-dvip-cable-1-hdmi-1 amplifier-1-hdmi-17)
  (compatible hdmi-dvip-cable-1-hdmi-1 amplifier-1-hdmi-18)
  (compatible hdmi-dvip-cable-1-hdmi-1 amplifier-1-hdmi-19)
  (compatible hdmi-dvip-cable-1-dvi-2 dvi-cable-1-dvi-1)
  (compatible hdmi-dvip-cable-1-dvi-2 dvi-cable-1-dvi-2)
  (compatible hdmi-dvip-cable-1-dvi-2 hdmi-dvi-cable-1-dvi-2)
  (compatible hdmi-dvip-cable-2-hdmi-1 blu-ray-1-hdmi-1)
  (compatible hdmi-dvip-cable-2-hdmi-1 tv-1-hdmi-1)
  (compatible hdmi-dvip-cable-2-hdmi-1 tv-1-hdmi-2)
  (compatible hdmi-dvip-cable-2-hdmi-1 tv-1-hdmi-3)
  (compatible hdmi-dvip-cable-2-hdmi-1 tv-1-hdmi-4)
  (compatible hdmi-dvip-cable-2-hdmi-1 amplifier-1-hdmi-13)
  (compatible hdmi-dvip-cable-2-hdmi-1 amplifier-1-hdmi-14)
  (compatible hdmi-dvip-cable-2-hdmi-1 amplifier-1-hdmi-15)
  (compatible hdmi-dvip-cable-2-hdmi-1 amplifier-1-hdmi-16)
  (compatible hdmi-dvip-cable-2-hdmi-1 amplifier-1-hdmi-17)
  (compatible hdmi-dvip-cable-2-hdmi-1 amplifier-1-hdmi-18)
  (compatible hdmi-dvip-cable-2-hdmi-1 amplifier-1-hdmi-19)
  (compatible hdmi-dvip-cable-2-dvi-2 dvi-cable-1-dvi-1)
  (compatible hdmi-dvip-cable-2-dvi-2 dvi-cable-1-dvi-2)
  (compatible hdmi-dvip-cable-2-dvi-2 hdmi-dvi-cable-1-dvi-2)
  (compatible spdif-cable-1-spdif-1 tv-1-spdif-9)
  (compatible spdif-cable-1-spdif-1 amplifier-1-spdif-20)
  (compatible spdif-cable-1-spdif-2 tv-1-spdif-9)
  (compatible spdif-cable-1-spdif-2 amplifier-1-spdif-20)
  (compatible blu-ray-1-hdmi-1 hdmi-cable-1-hdmi-1)
  (compatible blu-ray-1-hdmi-1 hdmi-cable-1-hdmi-2)
  (compatible blu-ray-1-hdmi-1 hdmi-cable-2-hdmi-1)
  (compatible blu-ray-1-hdmi-1 hdmi-cable-2-hdmi-2)
  (compatible blu-ray-1-hdmi-1 hdmi-dvi-cable-1-hdmi-1)
  (compatible blu-ray-1-hdmi-1 hdmi-dvip-cable-1-hdmi-1)
  (compatible blu-ray-1-hdmi-1 hdmi-dvip-cable-2-hdmi-1)
  (compatible blu-ray-1-cinch-2 scart-to-cinch-cable-1-cinch-2)
  (compatible blu-ray-1-cinch-2 scart-to-cinch-cable-1-cinch-3)
  (compatible blu-ray-1-cinch-2 cinch-cable-1-cinch-1)
  (compatible blu-ray-1-cinch-2 cinch-cable-1-cinch-2)
  (compatible blu-ray-1-cinch-2 cinch-cable-2-cinch-1)
  (compatible blu-ray-1-cinch-2 cinch-cable-2-cinch-2)
  (compatible blu-ray-1-cinch-2 cinch-cable-3-cinch-1)
  (compatible blu-ray-1-cinch-2 cinch-cable-3-cinch-2)
  (compatible blu-ray-1-cinch-2 cinch-cable-4-cinch-1)
  (compatible blu-ray-1-cinch-2 cinch-cable-4-cinch-2)
  (compatible blu-ray-1-cinch-2 headphone-cinch-cable-1-cinch-1)
  (compatible blu-ray-1-cinch-3 scart-to-cinch-cable-1-cinch-2)
  (compatible blu-ray-1-cinch-3 scart-to-cinch-cable-1-cinch-3)
  (compatible blu-ray-1-cinch-3 cinch-cable-1-cinch-1)
  (compatible blu-ray-1-cinch-3 cinch-cable-1-cinch-2)
  (compatible blu-ray-1-cinch-3 cinch-cable-2-cinch-1)
  (compatible blu-ray-1-cinch-3 cinch-cable-2-cinch-2)
  (compatible blu-ray-1-cinch-3 cinch-cable-3-cinch-1)
  (compatible blu-ray-1-cinch-3 cinch-cable-3-cinch-2)
  (compatible blu-ray-1-cinch-3 cinch-cable-4-cinch-1)
  (compatible blu-ray-1-cinch-3 cinch-cable-4-cinch-2)
  (compatible blu-ray-1-cinch-3 headphone-cinch-cable-1-cinch-1)
  (compatible sat-receiver-1-scart-1 scart-to-cinch-cable-1-scart-1)
  (compatible sat-receiver-1-scart-2 scart-to-cinch-cable-1-scart-1)
  (compatible sat-receiver-1-scart-3 scart-to-cinch-cable-1-scart-1)
  (compatible sat-receiver-1-cinch-4 scart-to-cinch-cable-1-cinch-2)
  (compatible sat-receiver-1-cinch-4 scart-to-cinch-cable-1-cinch-3)
  (compatible sat-receiver-1-cinch-4 cinch-cable-1-cinch-1)
  (compatible sat-receiver-1-cinch-4 cinch-cable-1-cinch-2)
  (compatible sat-receiver-1-cinch-4 cinch-cable-2-cinch-1)
  (compatible sat-receiver-1-cinch-4 cinch-cable-2-cinch-2)
  (compatible sat-receiver-1-cinch-4 cinch-cable-3-cinch-1)
  (compatible sat-receiver-1-cinch-4 cinch-cable-3-cinch-2)
  (compatible sat-receiver-1-cinch-4 cinch-cable-4-cinch-1)
  (compatible sat-receiver-1-cinch-4 cinch-cable-4-cinch-2)
  (compatible sat-receiver-1-cinch-4 headphone-cinch-cable-1-cinch-1)
  (compatible sat-receiver-1-cinch-5 scart-to-cinch-cable-1-cinch-2)
  (compatible sat-receiver-1-cinch-5 scart-to-cinch-cable-1-cinch-3)
  (compatible sat-receiver-1-cinch-5 cinch-cable-1-cinch-1)
  (compatible sat-receiver-1-cinch-5 cinch-cable-1-cinch-2)
  (compatible sat-receiver-1-cinch-5 cinch-cable-2-cinch-1)
  (compatible sat-receiver-1-cinch-5 cinch-cable-2-cinch-2)
  (compatible sat-receiver-1-cinch-5 cinch-cable-3-cinch-1)
  (compatible sat-receiver-1-cinch-5 cinch-cable-3-cinch-2)
  (compatible sat-receiver-1-cinch-5 cinch-cable-4-cinch-1)
  (compatible sat-receiver-1-cinch-5 cinch-cable-4-cinch-2)
  (compatible sat-receiver-1-cinch-5 headphone-cinch-cable-1-cinch-1)
  (compatible sat-receiver-1-cinch-6 scart-to-cinch-cable-1-cinch-2)
  (compatible sat-receiver-1-cinch-6 scart-to-cinch-cable-1-cinch-3)
  (compatible sat-receiver-1-cinch-6 cinch-cable-1-cinch-1)
  (compatible sat-receiver-1-cinch-6 cinch-cable-1-cinch-2)
  (compatible sat-receiver-1-cinch-6 cinch-cable-2-cinch-1)
  (compatible sat-receiver-1-cinch-6 cinch-cable-2-cinch-2)
  (compatible sat-receiver-1-cinch-6 cinch-cable-3-cinch-1)
  (compatible sat-receiver-1-cinch-6 cinch-cable-3-cinch-2)
  (compatible sat-receiver-1-cinch-6 cinch-cable-4-cinch-1)
  (compatible sat-receiver-1-cinch-6 cinch-cable-4-cinch-2)
  (compatible sat-receiver-1-cinch-6 headphone-cinch-cable-1-cinch-1)
  (compatible tv-1-hdmi-1 hdmi-cable-1-hdmi-1)
  (compatible tv-1-hdmi-1 hdmi-cable-1-hdmi-2)
  (compatible tv-1-hdmi-1 hdmi-cable-2-hdmi-1)
  (compatible tv-1-hdmi-1 hdmi-cable-2-hdmi-2)
  (compatible tv-1-hdmi-1 hdmi-dvi-cable-1-hdmi-1)
  (compatible tv-1-hdmi-1 hdmi-dvip-cable-1-hdmi-1)
  (compatible tv-1-hdmi-1 hdmi-dvip-cable-2-hdmi-1)
  (compatible tv-1-hdmi-2 hdmi-cable-1-hdmi-1)
  (compatible tv-1-hdmi-2 hdmi-cable-1-hdmi-2)
  (compatible tv-1-hdmi-2 hdmi-cable-2-hdmi-1)
  (compatible tv-1-hdmi-2 hdmi-cable-2-hdmi-2)
  (compatible tv-1-hdmi-2 hdmi-dvi-cable-1-hdmi-1)
  (compatible tv-1-hdmi-2 hdmi-dvip-cable-1-hdmi-1)
  (compatible tv-1-hdmi-2 hdmi-dvip-cable-2-hdmi-1)
  (compatible tv-1-hdmi-3 hdmi-cable-1-hdmi-1)
  (compatible tv-1-hdmi-3 hdmi-cable-1-hdmi-2)
  (compatible tv-1-hdmi-3 hdmi-cable-2-hdmi-1)
  (compatible tv-1-hdmi-3 hdmi-cable-2-hdmi-2)
  (compatible tv-1-hdmi-3 hdmi-dvi-cable-1-hdmi-1)
  (compatible tv-1-hdmi-3 hdmi-dvip-cable-1-hdmi-1)
  (compatible tv-1-hdmi-3 hdmi-dvip-cable-2-hdmi-1)
  (compatible tv-1-hdmi-4 hdmi-cable-1-hdmi-1)
  (compatible tv-1-hdmi-4 hdmi-cable-1-hdmi-2)
  (compatible tv-1-hdmi-4 hdmi-cable-2-hdmi-1)
  (compatible tv-1-hdmi-4 hdmi-cable-2-hdmi-2)
  (compatible tv-1-hdmi-4 hdmi-dvi-cable-1-hdmi-1)
  (compatible tv-1-hdmi-4 hdmi-dvip-cable-1-hdmi-1)
  (compatible tv-1-hdmi-4 hdmi-dvip-cable-2-hdmi-1)
  (compatible tv-1-cinch-5 scart-to-cinch-cable-1-cinch-2)
  (compatible tv-1-cinch-5 scart-to-cinch-cable-1-cinch-3)
  (compatible tv-1-cinch-5 cinch-cable-1-cinch-1)
  (compatible tv-1-cinch-5 cinch-cable-1-cinch-2)
  (compatible tv-1-cinch-5 cinch-cable-2-cinch-1)
  (compatible tv-1-cinch-5 cinch-cable-2-cinch-2)
  (compatible tv-1-cinch-5 cinch-cable-3-cinch-1)
  (compatible tv-1-cinch-5 cinch-cable-3-cinch-2)
  (compatible tv-1-cinch-5 cinch-cable-4-cinch-1)
  (compatible tv-1-cinch-5 cinch-cable-4-cinch-2)
  (compatible tv-1-cinch-5 headphone-cinch-cable-1-cinch-1)
  (compatible tv-1-cinch-6 scart-to-cinch-cable-1-cinch-2)
  (compatible tv-1-cinch-6 scart-to-cinch-cable-1-cinch-3)
  (compatible tv-1-cinch-6 cinch-cable-1-cinch-1)
  (compatible tv-1-cinch-6 cinch-cable-1-cinch-2)
  (compatible tv-1-cinch-6 cinch-cable-2-cinch-1)
  (compatible tv-1-cinch-6 cinch-cable-2-cinch-2)
  (compatible tv-1-cinch-6 cinch-cable-3-cinch-1)
  (compatible tv-1-cinch-6 cinch-cable-3-cinch-2)
  (compatible tv-1-cinch-6 cinch-cable-4-cinch-1)
  (compatible tv-1-cinch-6 cinch-cable-4-cinch-2)
  (compatible tv-1-cinch-6 headphone-cinch-cable-1-cinch-1)
  (compatible tv-1-headphone-8 headphone-cinch-cable-1-headphone-2)
  (compatible tv-1-spdif-9 spdif-cable-1-spdif-1)
  (compatible tv-1-spdif-9 spdif-cable-1-spdif-2)
  (compatible amplifier-1-cinch-1 scart-to-cinch-cable-1-cinch-2)
  (compatible amplifier-1-cinch-1 scart-to-cinch-cable-1-cinch-3)
  (compatible amplifier-1-cinch-1 cinch-cable-1-cinch-1)
  (compatible amplifier-1-cinch-1 cinch-cable-1-cinch-2)
  (compatible amplifier-1-cinch-1 cinch-cable-2-cinch-1)
  (compatible amplifier-1-cinch-1 cinch-cable-2-cinch-2)
  (compatible amplifier-1-cinch-1 cinch-cable-3-cinch-1)
  (compatible amplifier-1-cinch-1 cinch-cable-3-cinch-2)
  (compatible amplifier-1-cinch-1 cinch-cable-4-cinch-1)
  (compatible amplifier-1-cinch-1 cinch-cable-4-cinch-2)
  (compatible amplifier-1-cinch-1 headphone-cinch-cable-1-cinch-1)
  (compatible amplifier-1-cinch-2 scart-to-cinch-cable-1-cinch-2)
  (compatible amplifier-1-cinch-2 scart-to-cinch-cable-1-cinch-3)
  (compatible amplifier-1-cinch-2 cinch-cable-1-cinch-1)
  (compatible amplifier-1-cinch-2 cinch-cable-1-cinch-2)
  (compatible amplifier-1-cinch-2 cinch-cable-2-cinch-1)
  (compatible amplifier-1-cinch-2 cinch-cable-2-cinch-2)
  (compatible amplifier-1-cinch-2 cinch-cable-3-cinch-1)
  (compatible amplifier-1-cinch-2 cinch-cable-3-cinch-2)
  (compatible amplifier-1-cinch-2 cinch-cable-4-cinch-1)
  (compatible amplifier-1-cinch-2 cinch-cable-4-cinch-2)
  (compatible amplifier-1-cinch-2 headphone-cinch-cable-1-cinch-1)
  (compatible amplifier-1-cinch-3 scart-to-cinch-cable-1-cinch-2)
  (compatible amplifier-1-cinch-3 scart-to-cinch-cable-1-cinch-3)
  (compatible amplifier-1-cinch-3 cinch-cable-1-cinch-1)
  (compatible amplifier-1-cinch-3 cinch-cable-1-cinch-2)
  (compatible amplifier-1-cinch-3 cinch-cable-2-cinch-1)
  (compatible amplifier-1-cinch-3 cinch-cable-2-cinch-2)
  (compatible amplifier-1-cinch-3 cinch-cable-3-cinch-1)
  (compatible amplifier-1-cinch-3 cinch-cable-3-cinch-2)
  (compatible amplifier-1-cinch-3 cinch-cable-4-cinch-1)
  (compatible amplifier-1-cinch-3 cinch-cable-4-cinch-2)
  (compatible amplifier-1-cinch-3 headphone-cinch-cable-1-cinch-1)
  (compatible amplifier-1-cinch-4 scart-to-cinch-cable-1-cinch-2)
  (compatible amplifier-1-cinch-4 scart-to-cinch-cable-1-cinch-3)
  (compatible amplifier-1-cinch-4 cinch-cable-1-cinch-1)
  (compatible amplifier-1-cinch-4 cinch-cable-1-cinch-2)
  (compatible amplifier-1-cinch-4 cinch-cable-2-cinch-1)
  (compatible amplifier-1-cinch-4 cinch-cable-2-cinch-2)
  (compatible amplifier-1-cinch-4 cinch-cable-3-cinch-1)
  (compatible amplifier-1-cinch-4 cinch-cable-3-cinch-2)
  (compatible amplifier-1-cinch-4 cinch-cable-4-cinch-1)
  (compatible amplifier-1-cinch-4 cinch-cable-4-cinch-2)
  (compatible amplifier-1-cinch-4 headphone-cinch-cable-1-cinch-1)
  (compatible amplifier-1-cinch-5 scart-to-cinch-cable-1-cinch-2)
  (compatible amplifier-1-cinch-5 scart-to-cinch-cable-1-cinch-3)
  (compatible amplifier-1-cinch-5 cinch-cable-1-cinch-1)
  (compatible amplifier-1-cinch-5 cinch-cable-1-cinch-2)
  (compatible amplifier-1-cinch-5 cinch-cable-2-cinch-1)
  (compatible amplifier-1-cinch-5 cinch-cable-2-cinch-2)
  (compatible amplifier-1-cinch-5 cinch-cable-3-cinch-1)
  (compatible amplifier-1-cinch-5 cinch-cable-3-cinch-2)
  (compatible amplifier-1-cinch-5 cinch-cable-4-cinch-1)
  (compatible amplifier-1-cinch-5 cinch-cable-4-cinch-2)
  (compatible amplifier-1-cinch-5 headphone-cinch-cable-1-cinch-1)
  (compatible amplifier-1-cinch-6 scart-to-cinch-cable-1-cinch-2)
  (compatible amplifier-1-cinch-6 scart-to-cinch-cable-1-cinch-3)
  (compatible amplifier-1-cinch-6 cinch-cable-1-cinch-1)
  (compatible amplifier-1-cinch-6 cinch-cable-1-cinch-2)
  (compatible amplifier-1-cinch-6 cinch-cable-2-cinch-1)
  (compatible amplifier-1-cinch-6 cinch-cable-2-cinch-2)
  (compatible amplifier-1-cinch-6 cinch-cable-3-cinch-1)
  (compatible amplifier-1-cinch-6 cinch-cable-3-cinch-2)
  (compatible amplifier-1-cinch-6 cinch-cable-4-cinch-1)
  (compatible amplifier-1-cinch-6 cinch-cable-4-cinch-2)
  (compatible amplifier-1-cinch-6 headphone-cinch-cable-1-cinch-1)
  (compatible amplifier-1-cinch-7 scart-to-cinch-cable-1-cinch-2)
  (compatible amplifier-1-cinch-7 scart-to-cinch-cable-1-cinch-3)
  (compatible amplifier-1-cinch-7 cinch-cable-1-cinch-1)
  (compatible amplifier-1-cinch-7 cinch-cable-1-cinch-2)
  (compatible amplifier-1-cinch-7 cinch-cable-2-cinch-1)
  (compatible amplifier-1-cinch-7 cinch-cable-2-cinch-2)
  (compatible amplifier-1-cinch-7 cinch-cable-3-cinch-1)
  (compatible amplifier-1-cinch-7 cinch-cable-3-cinch-2)
  (compatible amplifier-1-cinch-7 cinch-cable-4-cinch-1)
  (compatible amplifier-1-cinch-7 cinch-cable-4-cinch-2)
  (compatible amplifier-1-cinch-7 headphone-cinch-cable-1-cinch-1)
  (compatible amplifier-1-hdmi-13 hdmi-cable-1-hdmi-1)
  (compatible amplifier-1-hdmi-13 hdmi-cable-1-hdmi-2)
  (compatible amplifier-1-hdmi-13 hdmi-cable-2-hdmi-1)
  (compatible amplifier-1-hdmi-13 hdmi-cable-2-hdmi-2)
  (compatible amplifier-1-hdmi-13 hdmi-dvi-cable-1-hdmi-1)
  (compatible amplifier-1-hdmi-13 hdmi-dvip-cable-1-hdmi-1)
  (compatible amplifier-1-hdmi-13 hdmi-dvip-cable-2-hdmi-1)
  (compatible amplifier-1-hdmi-14 hdmi-cable-1-hdmi-1)
  (compatible amplifier-1-hdmi-14 hdmi-cable-1-hdmi-2)
  (compatible amplifier-1-hdmi-14 hdmi-cable-2-hdmi-1)
  (compatible amplifier-1-hdmi-14 hdmi-cable-2-hdmi-2)
  (compatible amplifier-1-hdmi-14 hdmi-dvi-cable-1-hdmi-1)
  (compatible amplifier-1-hdmi-14 hdmi-dvip-cable-1-hdmi-1)
  (compatible amplifier-1-hdmi-14 hdmi-dvip-cable-2-hdmi-1)
  (compatible amplifier-1-hdmi-15 hdmi-cable-1-hdmi-1)
  (compatible amplifier-1-hdmi-15 hdmi-cable-1-hdmi-2)
  (compatible amplifier-1-hdmi-15 hdmi-cable-2-hdmi-1)
  (compatible amplifier-1-hdmi-15 hdmi-cable-2-hdmi-2)
  (compatible amplifier-1-hdmi-15 hdmi-dvi-cable-1-hdmi-1)
  (compatible amplifier-1-hdmi-15 hdmi-dvip-cable-1-hdmi-1)
  (compatible amplifier-1-hdmi-15 hdmi-dvip-cable-2-hdmi-1)
  (compatible amplifier-1-hdmi-16 hdmi-cable-1-hdmi-1)
  (compatible amplifier-1-hdmi-16 hdmi-cable-1-hdmi-2)
  (compatible amplifier-1-hdmi-16 hdmi-cable-2-hdmi-1)
  (compatible amplifier-1-hdmi-16 hdmi-cable-2-hdmi-2)
  (compatible amplifier-1-hdmi-16 hdmi-dvi-cable-1-hdmi-1)
  (compatible amplifier-1-hdmi-16 hdmi-dvip-cable-1-hdmi-1)
  (compatible amplifier-1-hdmi-16 hdmi-dvip-cable-2-hdmi-1)
  (compatible amplifier-1-hdmi-17 hdmi-cable-1-hdmi-1)
  (compatible amplifier-1-hdmi-17 hdmi-cable-1-hdmi-2)
  (compatible amplifier-1-hdmi-17 hdmi-cable-2-hdmi-1)
  (compatible amplifier-1-hdmi-17 hdmi-cable-2-hdmi-2)
  (compatible amplifier-1-hdmi-17 hdmi-dvi-cable-1-hdmi-1)
  (compatible amplifier-1-hdmi-17 hdmi-dvip-cable-1-hdmi-1)
  (compatible amplifier-1-hdmi-17 hdmi-dvip-cable-2-hdmi-1)
  (compatible amplifier-1-hdmi-18 hdmi-cable-1-hdmi-1)
  (compatible amplifier-1-hdmi-18 hdmi-cable-1-hdmi-2)
  (compatible amplifier-1-hdmi-18 hdmi-cable-2-hdmi-1)
  (compatible amplifier-1-hdmi-18 hdmi-cable-2-hdmi-2)
  (compatible amplifier-1-hdmi-18 hdmi-dvi-cable-1-hdmi-1)
  (compatible amplifier-1-hdmi-18 hdmi-dvip-cable-1-hdmi-1)
  (compatible amplifier-1-hdmi-18 hdmi-dvip-cable-2-hdmi-1)
  (compatible amplifier-1-hdmi-19 hdmi-cable-1-hdmi-1)
  (compatible amplifier-1-hdmi-19 hdmi-cable-1-hdmi-2)
  (compatible amplifier-1-hdmi-19 hdmi-cable-2-hdmi-1)
  (compatible amplifier-1-hdmi-19 hdmi-cable-2-hdmi-2)
  (compatible amplifier-1-hdmi-19 hdmi-dvi-cable-1-hdmi-1)
  (compatible amplifier-1-hdmi-19 hdmi-dvip-cable-1-hdmi-1)
  (compatible amplifier-1-hdmi-19 hdmi-dvip-cable-2-hdmi-1)
  (compatible amplifier-1-spdif-20 spdif-cable-1-spdif-1)
  (compatible amplifier-1-spdif-20 spdif-cable-1-spdif-2)
 )
)
